# Copyright 2017 Glen Joseph Fernandes
# (glenjofe@gmail.com)
#
# Distributed under the Boost Software License, Version 1.0.
# (http://www.boost.org/LICENSE_1_0.txt)

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - master
    - develop

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      TOOLSET: msvc-9.0,msvc-10.0,msvc-11.0,msvc-12.0

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      TOOLSET: msvc-14.0

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      TOOLSET: msvc-14.1
      STANDARD: 14,17

install:
  - git clone -b %APPVEYOR_REPO_BRANCH% https://github.com/boostorg/boost
  - cd boost
  - git submodule init libs/assert
  - git submodule init libs/config
  - git submodule init libs/core
  - git submodule init libs/static_assert
  - git submodule init libs/throw_exception
  - git submodule init tools/build
  - git submodule update
  - xcopy /s /e /q %APPVEYOR_BUILD_FOLDER%\include libs\align\include\
  - xcopy /s /e /q %APPVEYOR_BUILD_FOLDER%\test libs\align\test\
  - bootstrap
  - b2 headers

build: off

test_script:
  - if not "%STANDARD%" == "" set CXXSTD=cxxstd=%STANDARD%
  - b2 libs/align/test toolset=%TOOLSET% %CXXSTD%
